runtime: python39
entrypoint: gunicorn -b :$PORT app:app

instance_class: F1

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10

env_variables:
  ARTSY_CLIENT_ID: "your_client_id_here"
  ARTSY_CLIENT_SECRET: "your_client_secret_here" 